# TOML = Tom's Obvious, Minimal Language
# Tom Preston-Werner https://tom.preston-werner.com, Mitgruender von GitHub
# Erstes Release im Maerz 2013

[inventory.server]
# asgi = "uvicorn"
# asgi = "hypercorn"
# host-binding = "0.0.0.0"
port = 7302

[inventory.db]
# dialect = "postgresql"
dialect = "mysql"
# dialect = "sqlite"
username = "inventory"
name = "inventory"
password = "GentleCorp27.03.2025"
password-admin = "p"
host = "localhost"
# locust: auskommentieren
log-statements = true

[inventory.dev]
# z.B. DB neu laden
enabled = true

[inventory.excel]
enabled = true

[inventory.graphql]
# locust: auskommentieren
graphiql-enabled = true

[inventory.jwt]
# algorithm = "RS256"
# private-key = "private-key.pem"
# public-key = "public-key.pem"
# issuer = "https://hka.de/JuergenZimmermann"

[inventory.smtp]
enabled = false
host = "localhost"
# host = "fakesmtp"
port = 8025
# timeout = 1.0

[inventory.tls]
# key = "key.pem"
# certificate = "certificate.crt"
